### PR TITLE
Use CircleCI prebuilt image

### PR DESCRIPTION
**Pull request by brenetic**
Circle have newer prebuilt images which apparently spin up faster and are more stable.

https://circleci.com/docs/2.0/circleci-images/

### CODE REVIEW

**Review by tomas-stefano — APPROVED** [review]

**Comment by tomas-stefano** [comment]
@brenetic can we close this PR?

**Comment by brenetic** [comment]
well i think we should fix it as it's an actual testing failing for a reason

**Comment by tomas-stefano** [comment]
I see. Let's pair on this sometime for 20min anytime that we are both free?

**Comment by njseeto** [comment]
Will open a new branch and cherry pick this commit b9744a76badc96d21fa2650fd66e75685b4f3c55

**Pull request closed without merging**
