### PR TITLE
add dependabot config

### PR DESCRIPTION
**Pull request by asmega**

### CODE REVIEW

**Comment by solidgoldpig** [comment]
Need to double-check the pupeteer bump that will happen if we enable this without pinning it.

We definitely didn't want to use 1.18.1, but 1.19.0 looks like it's out now.

NB. We need to add a proper test of the pdf output so that we can know we can bump safely. I've been reviewing it manually because there have been quite a few ups and downs with puppeteer.

**Comment by solidgoldpig** [comment]
OK, checked puppeteer 1.19.0 and it seems to be working fine

**Comment by asmega** [comment]
dependabot is configured not to auto merge. you will get the choice whether or not you want to merge the suggested changes

**Comment by solidgoldpig** [comment]
I realise that Phil - I merely noted that (as with Immer that I just removed) we had a dependency that we would have wanted to fix. Fortunately, it looks like we don't need to.

**Pull request merged**
